services:
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx_conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx_conf/.htpasswd:/etc/nginx/.htpasswd
      - ./certs:/etc/nginx/certs
    depends_on:
      - wazuh.dashboard
    networks:
      - wazuh-net

  wazuh.indexer:
    build:
      context: .
      dockerfile: Dockerfile.indexer
    ports:
      - "9200:9200"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - wazuh-indexer-data:/var/lib/wazuh-indexer
    networks:
      - wazuh-net


  wazuh.manager:
    image: wazuh/wazuh-manager:4.9.0
    privileged: true
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - INDEXER_URL=http://wazuh.indexer:9200
      - FILEBEAT_SSL_VERIFICATION_MODE=none
      - API_USER=wazuh-wui
      - API_PASSWORD=wazuh-wui
    volumes:
      - wazuh-manager-data:/var/ossec/data
      - wazuh-manager-logs-data:/var/ossec/logs
      - wazuh-manager-etc-data:/var/ossec/etc
    depends_on:
      - wazuh.indexer
    networks:
      - wazuh-net

  wazuh.dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    restart: always
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=http://wazuh.indexer:9200
      - WAZUH_API_URL=https://wazuh.manager:55000
    volumes:
      - ./wazuh.yml:/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml:ro
    depends_on:
      - wazuh.indexer
      - wazuh.manager
    networks:
      - wazuh-net

  victim-node:
    build: ./sensor
    privileged: true
    restart: always
    environment:
      - WAZUH_MANAGER=wazuh.manager
    depends_on:
      - wazuh.manager
    networks:
      - wazuh-net

  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:8.9.0
    restart: always
    user: "0:0"
    ports:
      - "9600:9600"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - wazuh-manager-logs-data:/var/ossec/logs:ro
    depends_on:
      - wazuh.manager
      - wazuh.indexer
    networks:
      - wazuh-net

volumes:
  wazuh-indexer-data:
  wazuh-manager-data:
  wazuh-manager-logs-data:
  wazuh-manager-etc-data:

networks:
  wazuh-net:
    driver: bridge
